name: Jekyll Deploy

on:
  push:
    branches:
      # deploy on updates on main
      - main
  schedule:
    # redeploy every morning to update unpublished pages
    - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pushes to another repository
        uses: darkquasar/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_site'
          target-directory: '/'
          destination-github-username: 'wholon'
          destination-repository-name: 'wholon.github.io'
          user-email: 'holon.cn@gmail.com'
          target-branch: 'gh-pages'
          commit-message: '部署博客'
